# Generated by Django 4.1.7 on 2023-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_patientprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[("S", "Single"), ("M", "Married")],
                max_length=50,
                null=True,
            ),
        ),
    ]
