# Generated by Django 4.1.7 on 2023-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_patientprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="file_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
