# Generated by Django 4.1.7 on 2023-03-29 14:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_patientprofile_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recertion",
        ),
        migrations.CreateModel(
            name="Recprtion",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.user",),
            managers=[
                ("reception", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
