# Generated by Django 4.1.7 on 2023-03-29 15:32

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_delete_recertion_recprtion_patientprofile_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recprtion",
        ),
        migrations.CreateModel(
            name="Reception",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.user",),
            managers=[
                ("reception", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
