# Generated by Django 4.1.7 on 2023-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_delete_recprtion_reception"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
