# Generated by Django 4.1.7 on 2023-04-02 11:23

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointment",
            "0006_alter_doctor_membership_date_alter_offer_ending_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="doctor",
            managers=[
                ("daysIn", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="sanday",
            new_name="saturday",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="satrday",
            new_name="sunday",
        ),
        migrations.RenameField(
            model_name="doctor",
            old_name="wedensday",
            new_name="wednesday",
        ),
        migrations.RenameField(
            model_name="therapist",
            old_name="sanday",
            new_name="saturday",
        ),
        migrations.RenameField(
            model_name="therapist",
            old_name="satrday",
            new_name="sunday",
        ),
        migrations.RenameField(
            model_name="therapist",
            old_name="wedensday",
            new_name="wednesday",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="membership_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 14, 22, 49, 880180)
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="ending_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 14, 22, 49, 880180)
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 14, 22, 49, 880180)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 14, 22, 49, 880180)
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="membership_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 14, 22, 49, 880180)
            ),
        ),
    ]
