# Generated by Django 4.1.7 on 2023-04-02 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "appointment",
            "0008_alter_doctor_managers_alter_doctor_membership_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="device_appointment",
            name="attended",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="membership_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 15, 26, 34, 104583)
            ),
        ),
        migrations.AlterField(
            model_name="doctor_appointment",
            name="attended",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="offer",
            name="ending_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 15, 26, 34, 104583)
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 15, 26, 34, 104583)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 15, 26, 34, 104583)
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="membership_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 2, 15, 26, 34, 104583)
            ),
        ),
    ]
