# Generated by Django 4.1.7 on 2023-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0021_alter_post_publish_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="devices_photos/%Y/%m/%d/"
            ),
        ),
    ]
