# Generated by Django 4.1.7 on 2023-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0023_device_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
