# Generated by Django 4.1.7 on 2023-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0024_alter_offer_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="is_service",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="doctor",
            name="rate",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="cleanless",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="reception_rate",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="therapisting_rate",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="treatment_od_medical_staff",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="therapist",
            name="rate",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Normal"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                null=True,
            ),
        ),
    ]
