# Generated by Django 4.1.7 on 2023-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0025_device_is_service_doctor_rate_rate_cleanless_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_dev.jpg",
                null=True,
                upload_to="devices_photos/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_pic.jpg",
                null=True,
                upload_to="employee_photos/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_sec.png",
                null=True,
                upload_to="posts_photos/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_pic.jpg",
                null=True,
                upload_to="employee_photos/%Y/%m/%d/",
            ),
        ),
    ]
