# Generated by Django 4.1.7 on 2023-06-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0026_alter_device_photo_alter_doctor_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="device_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.device_appointment",
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="doctor_appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointment.doctor_appointment",
            ),
        ),
    ]
